---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: advanced-cluster-management
    namespace: open-cluster-management
spec:
    # renovate: datasource=custom.openshift-acm depName=red-hat-openshift-acm versioning=loose
    channel: release-2.12
    # renovate: datasource=custom.openshift-acm depName=red-hat-openshift-acm
    version: 2.12    
    # renovate: datasource=custom.openshift-acm depName=red-hat-openshift-acm versioning=loose
    version-loose: 2.12
    # renovate: datasource=custom.openshift-acm depName=red-hat-openshift-acm
    version-no: 2.12.2
    installPlanApproval: Automatic
    name: advanced-cluster-management
    source: redhat-operators
    sourceNamespace: openshift-marketplace